gitlab-ci: Use the new variants aware devel images
The generic Jupiter and Holo devel images have been deprecated in favor
of their variants aware counterpart.

Switch to these new images to avoid errors like:
```
error: failed retrieving file 'multilib.db' from
latest-pacman.steamos.cloud : The requested URL returned error: 401
```

Signed-off-by: Ludovico de Nittis <ludovico.denittis@collabora.com>